export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const INFO_MESSAGE = "INFO_MESSAGE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_ERROR_MESSAGE = "CLEAR_ERROR_MESSAGE";
export const CLEAR_SUCCESS_MESSAGE = "CLEAR_SUCCESS_MESSAGE";
export const CLEAR_INFO_MESSAGE = "CLEAR_INFO_MESSAGE";
