export const SET_ALL_GAME_AUTHORS = 'SET_ALL_GAME_AUTHORS';
export const UPDATE_GAME_AUTHOR_ARRAY = 'UPDATE_GAME_AUTHOR_ARRAY';
export const DELETE_GAME_AUTHOR = 'DELETE_GAME_AUTHOR';
export const SET_SELECTED_GAME_AUTHOR_DATA = 'SET_SELECTED_GAME_AUTHOR_DATA';