export const SET_ALL_USERS = 'SET_ALL_USERS';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_OPTION_FOR_ADMIN = 'SET_OPTION_FOR_ADMIN';
export const CLEAR_OPTION_FOR_ADMIN = 'CLEAR_OPTION_FOR_ADMIN';