export const AXIOS_SUCCESS_MESSAGE = 'AXIOS_SUCCESS_MESSAGE';
export const AXIOS_ERROR_MESSAGE = 'AXIOS_ERROR_MESSAGE';
export const AXIOS_POST_REQUEST = 'AXIOS_POST_REQUEST';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';